// Generated by scripts/record-fixtures.mjs. Do not edit by hand.
import type { FixtureFile, FixtureManifestEntry } from "@/data/fixtures";

const load = (importer: () => Promise<{ default: unknown }>) => () => importer().then((m) => m.default as FixtureFile);

export const FIXTURES: FixtureManifestEntry[] = [
  { id: "person-chat-greedy", kind: "loop", title: {"es":"Person · greedy","en":"Person · greedy"}, load: load(() => import("./person-chat-greedy.json")) },
  { id: "person-chat-t1-seed7", kind: "loop", title: {"es":"Person · T = 1 · semilla 7","en":"Person · T = 1 · seed 7"}, load: load(() => import("./person-chat-t1-seed7.json")) },
  { id: "capital-greedy", kind: "loop", title: {"es":"«The capital of France is» · greedy","en":"\"The capital of France is\" · greedy"}, load: load(() => import("./capital-greedy.json")) },
  { id: "fibonacci-greedy", kind: "loop", title: {"es":"«def fibonacci(n):» · greedy","en":"\"def fibonacci(n):\" · greedy"}, load: load(() => import("./fibonacci-greedy.json")) },
];
