// Generated by scripts/record-fixtures.mjs. Do not edit by hand.
import type { FixtureFile, FixtureManifestEntry } from "@/data/fixtures";

const load = (importer: () => Promise<{ default: unknown }>) => () => importer().then((m) => m.default as FixtureFile);

export const FIXTURES: FixtureManifestEntry[] = [
  { id: "person-chat", kind: "logits", title: {"es":"Prompt Person con template · paso 0","en":"Person prompt with template · step 0"}, load: load(() => import("./person-chat.json")) },
  { id: "tree-chat", kind: "logits", title: {"es":"Prompt Tree con template · paso 0","en":"Tree prompt with template · step 0"}, load: load(() => import("./tree-chat.json")) },
  { id: "capital", kind: "logits", title: {"es":"«The capital of France is»","en":"\"The capital of France is\""}, load: load(() => import("./capital.json")) },
  { id: "fibonacci", kind: "logits", title: {"es":"«def fibonacci(n):»","en":"\"def fibonacci(n):\""}, load: load(() => import("./fibonacci.json")) },
];
