// Generate design/tokens.css (and tokens.generated.ts) from design/tokens.<style>.json.
// Usage: node scripts/build-tokens.mjs [style]   (default: lab)
import { readFileSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const root = dirname(dirname(fileURLToPath(import.meta.url)));
const style = process.argv[2] ?? "lab";
const tokens = JSON.parse(readFileSync(join(root, "design", `tokens.${style}.json`), "utf8"));

function vars(mode) {
  const m = tokens.modes[mode];
  const lines = [
    ["--sf-page", m.surface.page], ["--sf-panel", m.surface.panel], ["--sf-raised", m.surface.raised],
    ["--ink-1", m.ink.primary], ["--ink-2", m.ink.secondary], ["--ink-3", m.ink.muted],
    ["--rule-1", m.rule.hairline], ["--rule-2", m.rule.strong],
    ["--accent", m.accent.base], ["--accent-soft", m.accent.soft], ["--accent-strong", m.accent.strong], ["--accent-ink", m.accent.ink],
    ["--series-model", m.series.model], ["--series-chosen", m.series.chosen], ["--series-third", m.series.third], ["--series-masked", m.series.masked],
    ["--status-good", m.status.good], ["--status-warn", m.status.warn], ["--status-critical", m.status.critical],
    ["--focus", m.focus],
  ];
  return lines.map(([k, v]) => `  ${k}: ${v};`).join("\n");
}

const shared = [
  `  --radius: ${tokens.space.radius}px;`,
  `  --radius-sm: ${tokens.space.radiusSm}px;`,
  `  --stroke: ${tokens.space.stroke}px;`,
  `  --hairline: ${tokens.space.hairline}px;`,
  `  --motion-fast: ${tokens.motion.fast}ms;`,
  `  --motion-base: ${tokens.motion.base}ms;`,
  `  --motion-slow: ${tokens.motion.slow}ms;`,
  ...Object.entries(tokens.scale).map(([k, v]) => `  --scale-${k}: ${v}px;`),
  ...tokens.tokenPastels.map((hex, i) => `  --pastel-${i}: ${hex};`),
].join("\n");

const css = `/* Generated by scripts/build-tokens.mjs from design/tokens.${style}.json. Do not edit by hand. */
/* Style: ${tokens.name}. Light is the bare :root; dark is a selected set of values, not an inversion. */
:root {
  color-scheme: light;
${vars("light")}
${shared}
}

@media (prefers-color-scheme: dark) {
  :root:not([data-theme="light"]) {
    color-scheme: dark;
${vars("dark").replace(/^/gm, "  ")}
  }
}

:root[data-theme="dark"],
[data-theme="dark"] {
  color-scheme: dark;
${vars("dark")}
}

[data-theme="light"] {
  color-scheme: light;
${vars("light")}
}
`;
writeFileSync(join(root, "design", "tokens.css"), css);

const ts = `// Generated by scripts/build-tokens.mjs from design/tokens.${style}.json. Do not edit by hand.
export const TOKENS = ${JSON.stringify(tokens, null, 2)} as const;
export type TokenMode = keyof typeof TOKENS.modes;
`;
writeFileSync(join(root, "design", "tokens.generated.ts"), ts);
console.log(`design/tokens.css and design/tokens.generated.ts written for style "${tokens.name}"`);
