// Generated by scripts/record-fixtures.mjs. Do not edit by hand.
import type { FixtureFile, FixtureManifestEntry } from "@/data/fixtures";

const load = (importer: () => Promise<{ default: unknown }>) => () => importer().then((m) => m.default as FixtureFile);

export const FIXTURES: FixtureManifestEntry[] = [
  { id: "person-json", kind: "tokenize", title: {"es":"{\"name\": \"Ada\", \"age\": 36}","en":"{\"name\": \"Ada\", \"age\": 36}"}, load: load(() => import("./person-json.json")) },
  { id: "person-json-gpt2", kind: "tokenize", title: {"es":"{\"name\": \"Ada\", \"age\": 36}","en":"{\"name\": \"Ada\", \"age\": 36}"}, load: load(() => import("./person-json-gpt2.json")) },
  { id: "numbers", kind: "tokenize", title: {"es":"In 1985 she paid 12.50 for 3 tickets and","en":"In 1985 she paid 12.50 for 3 tickets and"}, load: load(() => import("./numbers.json")) },
  { id: "numbers-gpt2", kind: "tokenize", title: {"es":"In 1985 she paid 12.50 for 3 tickets and","en":"In 1985 she paid 12.50 for 3 tickets and"}, load: load(() => import("./numbers-gpt2.json")) },
  { id: "code", kind: "tokenize", title: {"es":"def fibonacci(n):\n    return n if n < 2 ","en":"def fibonacci(n):\n    return n if n < 2 "}, load: load(() => import("./code.json")) },
  { id: "code-gpt2", kind: "tokenize", title: {"es":"def fibonacci(n):\n    return n if n < 2 ","en":"def fibonacci(n):\n    return n if n < 2 "}, load: load(() => import("./code-gpt2.json")) },
  { id: "spanish", kind: "tokenize", title: {"es":"El español paga más tokens: mañana, niño","en":"El español paga más tokens: mañana, niño"}, load: load(() => import("./spanish.json")) },
  { id: "spanish-gpt2", kind: "tokenize", title: {"es":"El español paga más tokens: mañana, niño","en":"El español paga más tokens: mañana, niño"}, load: load(() => import("./spanish-gpt2.json")) },
  { id: "en-sentence", kind: "tokenize", title: {"es":"The model reads and writes whole tokens,","en":"The model reads and writes whole tokens,"}, load: load(() => import("./en-sentence.json")) },
  { id: "en-sentence-gpt2", kind: "tokenize", title: {"es":"The model reads and writes whole tokens,","en":"The model reads and writes whole tokens,"}, load: load(() => import("./en-sentence-gpt2.json")) },
  { id: "es-sentence", kind: "tokenize", title: {"es":"El modelo lee y escribe tokens enteros, ","en":"El modelo lee y escribe tokens enteros, "}, load: load(() => import("./es-sentence.json")) },
  { id: "es-sentence-gpt2", kind: "tokenize", title: {"es":"El modelo lee y escribe tokens enteros, ","en":"El modelo lee y escribe tokens enteros, "}, load: load(() => import("./es-sentence-gpt2.json")) },
  { id: "person-prompt-template", kind: "tokenize", title: {"es":"Prompt Person con chat template","en":"Person prompt with the chat template"}, load: load(() => import("./person-prompt-template.json")) },
  { id: "person-prompt", kind: "tokenize", title: {"es":"Prompt Person sin template","en":"Person prompt without the template"}, load: load(() => import("./person-prompt.json")) },
];
