// Generated by scripts/record-fixtures.mjs. Do not edit by hand.
import type { FixtureFile, FixtureManifestEntry } from "@/data/fixtures";

const load = (importer: () => Promise<{ default: unknown }>) => () => importer().then((m) => m.default as FixtureFile);

export const FIXTURES: FixtureManifestEntry[] = [
  { id: "person-sp", kind: "experiment", title: {"es":"Person · schema en el prompt · 20 por modo","en":"Person · schema in the prompt · 20 per mode"}, load: load(() => import("./person-sp.json")) },
  { id: "invoice-sp", kind: "experiment", title: {"es":"Invoice · schema en el prompt · 20 por modo","en":"Invoice · schema in the prompt · 20 per mode"}, load: load(() => import("./invoice-sp.json")) },
  { id: "person-nosp", kind: "experiment", title: {"es":"Person · sin schema en el prompt · 20 por modo","en":"Person · no schema in the prompt · 20 per mode"}, load: load(() => import("./person-nosp.json")) },
  { id: "invoice-nosp", kind: "experiment", title: {"es":"Invoice · sin schema en el prompt · 20 por modo","en":"Invoice · no schema in the prompt · 20 per mode"}, load: load(() => import("./invoice-nosp.json")) },
];
