// Generated by scripts/record-fixtures.mjs. Do not edit by hand.
import type { FixtureFile, FixtureManifestEntry } from "@/data/fixtures";

const load = (importer: () => Promise<{ default: unknown }>) => () => importer().then((m) => m.default as FixtureFile);

export const FIXTURES: FixtureManifestEntry[] = [
  { id: "person-dev", kind: "experiment", title: {"es":"Person · 8 corridas por modo (desarrollo)","en":"Person · 8 runs per mode (development)"}, load: load(() => import("./person-dev.json")) },
];
